In [1]:
import numpy as np
print(np.__version__)
np.show_config()

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/HP/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/HP/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/HP/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/HP/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/HP/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/HP/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/HP/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/HP/anaconda3\\Library\\include']


In [2]:
#How to create an empty and a full NumPy arrayHow to create an empty and a full NumPy 
empty =np.array((3,4), dtype=int)
print(empty)

full_arr = np.full([3,4],55, dtype=int)
print(full_arr)

[3 4]
[[55 55 55 55]
 [55 55 55 55]
 [55 55 55 55]]


In [3]:
#array creatiom
arr =np.arange(8)
print(arr)

arr1 = np.arange(10,15)-10+1
print(arr1)

[0 1 2 3 4 5 6 7]
[1 2 3 4 5]


In [4]:
###Create a Numpy array filled with all zeros
zero_arr = np.zeros([3,4],dtype=int)
print(zero_arr)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [5]:
one_arr = np.ones([3,2],dtype=int)
print(one_arr)

[[1 1]
 [1 1]
 [1 1]]


In [6]:
#Check whether a Numpy array contains a specified row
arr = np.array([[1, 2, 3, 4, 5],
                   [6, 7, 8, 9, 10],
                   [11, 12, 13, 14, 15],
                   [16, 17, 18, 19, 20]
                   ])
print([1, 2, 3, 4, 5] in arr.tolist())
print([16, 17, 20, 19, 18] in arr.tolist())
print([3, 2, 5, -4, 5] in arr.tolist())
print([11, 12, 13, 14, 15] in arr.tolist())

True
False
False
True


In [7]:
#How to Remove rows in Numpy array that contains non-numeric values
n_arr = np.array([[10.5, 22.5, 3.8],[41, np.nan, np.nan]])
print(n_arr[~np.isnan(n_arr).any(axis=1)])

[[10.5 22.5  3.8]]


In [8]:
# remove single-dimensional entries from the shape of an array.
in_arr = np.array([[[2, 2, 2], [2, 2, 2]]])
out_arr = np.squeeze(in_arr) 
print(out_arr)
in_arr.shape
out_arr.shape

[[2 2 2]
 [2 2 2]]


(2, 3)

In [9]:
#Find the number of occurrences of a sequence in a NumPy array
arr = np.array([[2, 8, 9, 4], 
                   [9, 4, 9, 4],
                   [4, 5, 9, 7],
                   [2, 9, 4, 3]])
output = repr(arr).count("9, 4")
print(output)

4


In [10]:
len(np.arange(3,15))

arr = np.arange(3,15)
arr.size

12

In [11]:
arr = np.arange(3,30,3)
print(arr)

[ 3  6  9 12 15 18 21 24 27]


In [12]:
np.zeros(5)
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

### Two Dimensional Array

In [13]:
my_arr = np.arange(35)
my_arr.shape = (7,5)
my_arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [14]:
my_arr[3]

array([15, 16, 17, 18, 19])

In [15]:
my_arr[3,4]

19

In [16]:
row= 4
column =3
my_arr[row,column]

23

### Three Dimensional array

In [17]:
my_3D_arr = np.arange(70)
my_3D_arr.shape = (2,7,5)
my_3D_arr

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [18]:
my_3D_arr[1]

array([[35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69]])

In [19]:
my_3D_arr[1,3,4]

54

In [20]:
my_3D_arr.shape

(2, 7, 5)

In [21]:
my_3D_arr.size

70

In [22]:
my_3D_arr.dtype

dtype('int32')

In [23]:
my_3D_arr.ndim

3

In [24]:
5*my_3D_arr-1

array([[[ -1,   4,   9,  14,  19],
        [ 24,  29,  34,  39,  44],
        [ 49,  54,  59,  64,  69],
        [ 74,  79,  84,  89,  94],
        [ 99, 104, 109, 114, 119],
        [124, 129, 134, 139, 144],
        [149, 154, 159, 164, 169]],

       [[174, 179, 184, 189, 194],
        [199, 204, 209, 214, 219],
        [224, 229, 234, 239, 244],
        [249, 254, 259, 264, 269],
        [274, 279, 284, 289, 294],
        [299, 304, 309, 314, 319],
        [324, 329, 334, 339, 344]]])

In [25]:
left_mat =np.arange(6).reshape(2,3)
right_mat =np.arange(15).reshape(3,5)

In [26]:
my_3D_arr.sum(axis=2)

array([[ 10,  35,  60,  85, 110, 135, 160],
       [185, 210, 235, 260, 285, 310, 335]])

In [27]:
#Create a null vector of size 10
Z = np.zeros(10)
print(Z)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [28]:
#find memory size of any array
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


In [29]:
#create null vector of size 10 but 5 th value should be 1
z= np.zeros(10)
z[4] =1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [30]:
#Create a vector with values ranging from 10 to 49
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [31]:
#Reverse a vector first element becomes last
z=np.arange(50)
z= z[::-1]
print(z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [32]:
#Create a 3x3 matrix with values ranging from 0 to 8
z = np.arange(9).reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [33]:
#Find indices of non-zero elements from [1,2,0,0,4,0]
z = np.nonzero([1,2,0,0,4,0])
print(z)

(array([0, 1, 4], dtype=int64),)


In [34]:
#Create a 3x3 identity matrix 
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [35]:
#Create a 3x3x3 array with random values 
z = np.random.random((3,3,3))
print(z)

[[[0.7247445  0.25917559 0.28160773]
  [0.07550795 0.28018745 0.6533111 ]
  [0.51335774 0.72484314 0.00773649]]

 [[0.78093803 0.9249743  0.32547809]
  [0.22601757 0.07268065 0.80502634]
  [0.21568088 0.92182526 0.67737522]]

 [[0.30594892 0.23159127 0.03385446]
  [0.74253133 0.05397465 0.19658093]
  [0.24295002 0.66303898 0.38292038]]]


In [36]:
#Create a 10x10 array with random values and find the minimum and maximum values
Z = np.random.random((10,10))
Zmin= Z.min()
Zmax= Z.max()
print(Z)
print(Zmin, Zmax)

[[0.04631946 0.7708703  0.8129059  0.6556594  0.68167861 0.72126979
  0.6765168  0.79713074 0.55899371 0.4389769 ]
 [0.28332891 0.47167357 0.98651012 0.32026676 0.79878732 0.47115293
  0.58318855 0.50970178 0.81529999 0.7782607 ]
 [0.87015562 0.24012122 0.54851072 0.15941713 0.78728713 0.35800468
  0.62752153 0.36549188 0.126067   0.24090997]
 [0.33819894 0.18754143 0.48891965 0.61880001 0.83021039 0.87687874
  0.28217603 0.00903538 0.12856733 0.58477027]
 [0.72160178 0.43386417 0.91781125 0.64540811 0.17689668 0.99472297
  0.25824725 0.73918353 0.82196419 0.86614736]
 [0.42718221 0.54840827 0.66170138 0.82342817 0.56282747 0.8700894
  0.39130198 0.24500798 0.19148816 0.67816765]
 [0.95786934 0.43798755 0.32832139 0.03527026 0.66318608 0.68219563
  0.86163475 0.40329766 0.07936763 0.11393902]
 [0.4256372  0.42325147 0.6670202  0.75916617 0.7003336  0.63298168
  0.23102784 0.60059835 0.41278053 0.55549689]
 [0.6384431  0.61006399 0.89804198 0.59995274 0.64259818 0.77003532
  0.83309325 

In [37]:
#Create a random vector of size 30 and find the mean value
z = np.random.random(30)
min_z = z.mean()
print(z)
print(min_z)

[0.08155407 0.19027203 0.78631361 0.64711943 0.11061859 0.80669598
 0.57686679 0.58125828 0.68835662 0.53286042 0.6340302  0.38692643
 0.81234843 0.56589305 0.37443422 0.17266351 0.62092631 0.95835639
 0.86415464 0.945274   0.66931806 0.65719488 0.41234659 0.04629922
 0.86248705 0.56873654 0.55123817 0.5527961  0.32758335 0.65365501]
0.5546192651992415


In [38]:
#Create a 2d array with 1 on the border and 0 inside
z = np.ones((10,10))
z[1:-1,1:-1] =0
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [39]:
#How to add a border (filled with 0's) around an existing array? 
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)
# Using fancy indexing
Z[:, [0, -1]] = 0
Z[[0,-1],:] = 0
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [40]:
#What is the result of the following expression?
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1


print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [41]:
#Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [42]:
#Create a 8x8 matrix and fill it with a checkerboard pattern
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [43]:
#Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


In [44]:
#Create a checkerboard 4x4 matrix using the tile function
Z = np.tile( np.array([[0,1],[1,0]]), (2,2))
print(Z)

[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]


In [45]:
#Normalize a 5x5 random matrix
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[ 0.11269336 -0.6713061  -0.5143858  -0.4025332   0.64292238]
 [ 2.00081912 -0.35975927 -0.70924791 -1.54635002 -0.46994988]
 [ 0.86672181  0.65267596  0.53206595 -0.38308656  0.36005613]
 [-1.09839864  0.88074302  1.00654552 -1.29703606  1.56301933]
 [-0.01694491  1.98551343 -0.81789189 -0.77368852 -1.54319723]]


In [46]:
#Create a custom dtype that describes a color as four unsigned bytes (RGBA)
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


In [47]:
#Multiply a 5x3 matrix by a 3x2 matrix
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [48]:
#Given a 1D array, negate all elements which are between 3 and 8, in place
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


In [49]:
#What is the output of the following script?
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [50]:
#How to round away from zero a float array ?
Z = np.random.uniform(-10,+10,10)
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

[-7. -9. -2.  2.  3. 10. -3. -9.  2.  4.]


In [51]:
#Let's define a list in python.
np_heights = np.array([74, 75, 72, 72, 71])
np_heights = np_heights*2.54
np_heights

array([187.96, 190.5 , 182.88, 182.88, 180.34])

In [52]:
np1 = np.array([5,7,8])
np2 = np.array([7,8,4])
np =np1+np2
np

array([12, 15, 12])

### numpy Indexing and Slicing

In [53]:
import numpy as np 
a = np.arange(10) 
s = slice(2,7,2) 
print(a[s])

[2 4 6]


In [54]:
a = np.arange(10) 
b = a[5] 
print(b)

5


In [55]:
a = np.arange(10) 
print(a[2:5])

[2 3 4]


In [56]:
a = np.array([[1 ,2 ],[3 ,4 ],[5 ,6 ]])
print(a[[0 ,1 ,2 ],[0 ,0 ,1]])

[1 3 6]


In [57]:
a = np.array([10, 40, 80, 50, 100])
print(a[a>50])

[ 80 100]


In [58]:
a = np.array([10, 40, 80, 50, 100])
print(a[a%40==0]**2)

[1600 6400]


In [59]:
b = np.array([[5, 5],[4, 5],[16, 4]])
sumrow = b.sum(-1)
print(b[sumrow%10==0])

[[ 5  5]
 [16  4]]


### Arithmetic Operations

In [60]:
array1 = np.array([10,20,30,40,50])
array2 = np.arange(5)
array2

array([0, 1, 2, 3, 4])

In [61]:
array3 = array1 + array2
array3

array([10, 21, 32, 43, 54])

In [62]:
array4 = np.array([1,2,3,4])
array1 + array4

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [63]:
array1*2

array([ 20,  40,  60,  80, 100])

In [64]:
array1**2

array([ 100,  400,  900, 1600, 2500], dtype=int32)

In [65]:
np.power(array1,3)

array([  1000,   8000,  27000,  64000, 125000], dtype=int32)

In [66]:
array5 = array1 >= 30
array5

array([False, False,  True,  True,  True])

In [67]:
array1[array5]

array([30, 40, 50])

In [68]:
array1[array1 >= 30]

array([30, 40, 50])

### Arithmetic Operations on a 2D Array

In [69]:
A = np.array([[3,2],[0,1]])
B = np.array([[3,1],[2,1]])
print(A)

[[3 2]
 [0 1]]


In [70]:
A+B

array([[6, 3],
       [2, 2]])

In [71]:
A*B

array([[9, 2],
       [0, 1]])

In [72]:
A +=2

In [74]:
A @ B

array([[23,  9],
       [12,  5]])

In [75]:
array = np.random.random((2,2))
array

array([[0.1306855 , 0.476942  ],
       [0.28236449, 0.4417378 ]])

In [76]:
array.sum()

1.331729795087987

In [77]:
array.min()

0.13068550411076463

In [78]:
array.sum(axis=0)

array([0.41305  , 0.9186798])

In [79]:
array.min(axis=1)

array([0.1306855 , 0.28236449])

In [81]:
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])
print(a*b)

[  10  360  130 3000]


In [82]:
div_ans = a/b
print(div_ans)

[ 2.5        14.4         1.3         3.33333333]


In [83]:
mod_ans = np.mod(a, b)
print(mod_ans)

[ 1  2  3 10]


In [84]:
rem_ans=np.remainder(a,b)
print(rem_ans)

[ 1  2  3 10]


In [86]:
pow_ans = np.power(a, b)
print(pow_ans)

[        25 1934917632  419538377          0]


In [87]:
# Getting mean of all numbers in 'a'
mean_a = np.mean(a)
print(mean_a)
  
# Getting average of all numbers in 'b'
mean_b = np.average(b)
print(mean_b)
  
# Getting sum of all numbers in 'a'
sum_a = np.sum(a)
print(sum_a)
  
# Getting variance of all number in 'b'
var_b = np.var(b)
print(var_b)

47.5
11.75
190
119.1875


In [89]:
nums = np.arange(1, 17)
nums

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [90]:
nums3 = np.sqrt(nums)
print(nums3)

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766 3.31662479 3.46410162
 3.60555128 3.74165739 3.87298335 4.        ]


In [91]:
nums3 = np.sin(nums)
print(nums3)

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849 -0.54402111 -0.99999021 -0.53657292
  0.42016704  0.99060736  0.65028784 -0.28790332]


In [92]:
x = np.array([2,4])
y = np.array([1,3])

In [93]:
dot_product = 0
for a,b in zip(x,y):
    dot_product += a * b

print(dot_product)

14
